# Welcome to Jekyll!
title: PablorysT9N | Spanish Translator 
url: https://pabloryst9n.github.io/resume/
baseurl:

# Sass setting
sass:
  sass_dir: _sass
  style:    compressed

# Custom
lang: es
open: true                  # show or hide your resume
allow_search_engines: true  # allow your resume indexing by search engine, 'true' or 'false'
analytics:
  google:                   # google analytics
  cloudflare:               # cloudflare analytics
  umami:
    script:                 # umami analytics script src (Replace it with your own config)
    website_id:  # umami analytics website id (Replace it with your own config)
    domains:              # umami analytics domains (Replace it with your own config)
description:
open_graph:
  enable: true                        # enable open graph meta tags
  image: /assets/images/profile.png   # open graph image path

# Style
text_direction: ltr         # text direction, 'ltr' or 'rtl'
date_format: "%d-%m-%Y"     # date format
theme_color: "#CE6700"      # your favorite theme color
contact_delimiter: "·"      # contact delimiter, '·', '/' or '|'
section_icon: false          # section title icon, true or false
section_title: uppercase    # section title style, 'uppercase', 'lowercase', 'capitalize' or 'none'
section_align: start        # section title align, 'start', 'end' or 'center'
section_line: dashed        # section title line, 'solid', 'dashed' or 'none'
section_background: false   # section title backound, 'true' or 'false'
skill_level_icon: circle # skill rate icon, 'heart', 'star', 'circle' or 'lightbulb'
link_icon: true             # show link icon, 'true' or 'false'
site_footer: false           # show site footer, 'true' or 'false'

defaults:
 - scope:
      path: assets/favicons

plugins:
  - jekyll-seo-tag

safe: true

whitelist:
  - jekyll-seo-tag